// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Time, frame, polyfill;

  Time = require('./time').Time;

  polyfill = require('./polyfill');

  frame = {};

  frame.request = function(fn) {
    return polyfill.requestAnimationFrame(function() {
      return fn(new Time(start, last));
    });
  };

  frame.cancel = function(id) {
    return polyfill.cancelAnimationFrame(id);
  };

  module.exports = frame;

}).call(this);
