// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Time, frame, last, polyfill, start;

  Time = require('./time').Time;

  polyfill = require('./polyfill');

  frame = {};

  start = null;

  last = null;

  frame.request = function(fn) {
    return polyfill.requestAnimationFrame(function(timestamp) {
      if (start != null) {
        start = new Date();
      }
      fn(new Time(start, last));
      last = new Date();
      return last.setTime(timestamp);
    });
  };

  frame.cancel = function(id) {
    polyfill.cancelAnimationFrame(id);
    return start = null;
  };

  module.exports = frame;

}).call(this);
