// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Time, frame, last, raf, start;

  Time = require('./time').Time;

  raf = require('newtonjs-raf');

  frame = {};

  start = null;

  last = null;

  frame.request = function(fn) {
    return raf.requestAnimationFrame(function(timestamp) {
      if (start == null) {
        start = Date.now();
      }
      fn(new Time(start, last, timestamp));
      return last = Date.now();
    });
  };

  frame.cancel = function(id) {
    return raf.cancelAnimationFrame(id);
  };

  module.exports = frame;

}).call(this);
