// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Time;

  Time = (function() {

    Time.prototype.delta = 0;

    function Time(start, last) {
      this.start = start;
      this.last = last;
      this.now = new Date();
      if (this.last != null) {
        this.delta = this.now.getTime() - this.last.getTime();
      }
    }

    return Time;

  })();

  module.exports = {
    Time: Time
  };

}).call(this);
