// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Time;

  Time = (function() {

    Time.prototype.delta = 0;

    function Time(start, last, progress) {
      this.start = start;
      this.last = last;
      this.progress = progress;
      this.now = Date.now();
      if (this.last != null) {
        this.delta = this.now - this.last;
      }
    }

    return Time;

  })();

  module.exports = {
    Time: Time
  };

}).call(this);
